version: "3"

services:
  mysql:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: exchange
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
     - '3306:3306'
  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'